services:
  app-mongo:
    image: mongo:latest
    container_name: app-mongo
    hostname: app-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" -u admin -p admin --authenticationDatabase admin
      interval: 10s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - "app-network"

  iban-blacklist-service:
    container_name: iban-blacklist-service
    hostname: iban-blacklist-service
    depends_on:
      app-mongo:
        condition: service_healthy
    build:
      context: ./iban-blacklist-service/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      QUARKUS_HTTP_PORT: 8080
    networks:
      - "app-network"

  invoice-scanner-service:
    container_name: invoice-scanner-service
    hostname: invoice-scanner-service
    depends_on:
      - app-mongo
      - iban-blacklist-service
    build:
      context: ./invoice-scanner-service/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8088:8080"
    environment:
      QUARKUS_HTTP_PORT: 8080
    networks:
      - "app-network"

networks:
  app-network:
    driver: bridge
