quarkus:
    http:
      port: 8088

    keycloak:
      policy-enforcer:
          enable: true

    log:
        category:
            "io.quarkus.oidc":
                level: DEBUG
            "io.quarkus.security":
                level: DEBUG

    mongodb:
        connection-string: "mongodb://localhost:27217"
        database: "blacklist"
        credentials:
            auth-source: "blacklist"
            username: ${MONGO_BLACKLIST_USER_LOGIN}
            password: ${MONGO_BLACKLIST_USER_PASSWORD}

    oidc:
        application-type: service
        auth-server-url: "http://localhost:8888/realms/quark"
        client-id: ${OIDC_BLACKLIST_SVC_CLIENT_ID}
        credentials:
            secret: ${OIDC_BLACKLIST_SVC_CLIENT_SECRET}
