quarkus:
#    mongodb:
#        connection-string: "mongodb://app-mongo:27017"
#        database: "blacklist"
#        credentials:
#            auth-source: "blacklist"
#            username: "user"
#            password: "password"

    keycloak:
      policy-enforcer:
          enable: true

    oidc:
        application-type: service
        auth-server-url: "http://app-keycloak:8888/realms/quark"
        client-id: iban-blacklist-service
        credentials:
            secret: DeMCRauIdrX2XveQsgrOuw2Ul2yjsBOT

    log:
        category:
            "io.quarkus.oidc":
                level: DEBUG
            "io.quarkus.security":
                level: DEBUG
