quarkus:
    http:
      port: 8080

    keycloak:
        policy-enforcer:
            enable: true

    log:
        category:
            "io.quarkus.oidc":
                level: DEBUG
            "io.quarkus.security":
                level: DEBUG

    oidc:
        application-type: service
        auth-server-url: "${KC_AUTH_SERVER_URL}"
        client-id: "${OIDC_SCAN_SVC_CLIENT_ID}"
        credentials:
            secret: "${OIDC_SCAN_SVC_CLIENT_SECRET}"

    oidc-client:
        auth-server-url: "${KC_AUTH_SERVER_URL}"
        client-id: "${OIDC_CONFIDENTIAL_BLACKLIST_CLIENT_ID}"
        credentials:
            client-secret:
                method: POST
                value: "${OIDC_CONFIDENTIAL_BLACKLIST_CLIENT_SECRET}"
        grant:
            type: client
        grant-options:
            client:
                audience: "http://localhost:8080/"

    rest-client:
        blacklist-service:
            url: "http://localhost:8088/"

mp:
    messaging:
        incoming:
            invoice-urls:
                connector: smallrye-kafka
                topic: invoice-urls
                key:
                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value:
                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                auto:
                    offset:
                        reset: earliest
        outgoing:
            processed-invoices:
                connector: smallrye-kafka
                topic: processed-invoices
                key:
                    serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
    bootstrap:
        servers: "http://localhost:9092"
