quarkus:
    keycloak:
        policy-enforcer:
            enable: true
    oidc:
        auth-server-url: "http://app-keycloak:8888/realms/quark"
        client-id: "invoice-scanner-service"
        credentials:
            secret: "nm1Hv5Z6zHbkrYtzGJwlQBbly3mzBzlq"
    rest-client:
        blacklist-service:
            url: "http://iban-blacklist-service:8080/"

mp:
    messaging:
        incoming:
            invoice-urls:
                connector: smallrye-kafka
                topic: invoice-urls
                key:
                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value:
                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                auto:
                    offset:
                        reset: earliest
        outgoing:
            processed-invoices:
                connector: smallrye-kafka
                topic: processed-invoices
                key:
                    serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
    bootstrap:
        servers: franz-kafka:9092
