quarkus:
    http:
      port: 8080

    keycloak:
        policy-enforcer:
            enable: true

    log:
        category:
            "io.quarkus.oidc":
                level: DEBUG
            "io.quarkus.security":
                level: DEBUG

    oidc:
        application-type: service
        auth-server-url: "http://localhost:8888/realms/quark"
        client-id: invoice-scanner-service
        credentials:
            secret: "nm1Hv5Z6zHbkrYtzGJwlQBbly3mzBzlq"

    oidc-client:
        auth-server-url: "http://localhost:8888/realms/quark"
        client-id: confidential-blacklist
        credentials:
            client-secret:
                method: POST
                value: "FMg2cfCVR6pjGbwifLj1p75xPIUGzUnt"
        grant:
            type: client
        grant-options:
            client:
                audience: "http://localhost:8080/"

    rest-client:
        blacklist-service:
            url: "http://localhost:8088/"

mp:
    messaging:
        incoming:
            invoice-urls:
                connector: smallrye-kafka
                topic: invoice-urls
                key:
                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value:
                    deserializer: org.apache.kafka.common.serialization.StringDeserializer
                auto:
                    offset:
                        reset: earliest
        outgoing:
            processed-invoices:
                connector: smallrye-kafka
                topic: processed-invoices
                key:
                    serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
    bootstrap:
        servers: "http://localhost:9092"
