services:
    postgres:
        image: postgres:15-alpine
        container_name: keycloak-postgres
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - keycloak-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U keycloak"]
            interval: 30s
            timeout: 10s
            retries: 5

    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        command: start-dev --import-realm
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password

            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin

            KC_HOSTNAME: localhost
            KC_HTTP_ENABLED: true
        ports:
            - "8888:8080"
        volumes:
            - ./import:/opt/keycloak/data/import
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - keycloak-network

volumes:
    postgres_data:

networks:
    keycloak-network:
        driver: bridge
